hummingbird:
  image: birdhouse/hummingbird
  ports:
    - "48092:9001"
    - "38092:38092"
    - "8092:8092"
  environment:
    OUTPUT_PORT: 38092
  volumes:
    - data:/data
  volume_driver: local

