hummingbird:
  image: birdhouse/hummingbird
  ports:
    - "48092:9001"
    - "38092:38092"
    - "8092:8092"
  environment:
    HOSTNAME: localhost
    HTTP_PORT: 8092
    OUTPUT_PORT: 38092
  volumes:
    - /tmp/data:/opt/birdhouse/var/lib
    - /tmp/log:/opt/birdhouse/var/log
  volume_driver: local
