name: hummingbird
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=2.7.12
- pyopenssl
- cryptography
- pyyaml
- curl
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=3.2.6
- owslib
- nginx
- supervisor=3.3.1
- gunicorn
- gevent
- eventlet
# cdo
- cdo=1.7.1
#- python-cdo=1.3.0
- proj4=4.9.3  # fix cdo and qa-dkrz deps
#- jpeg=9b # fix cdo and qa-dkrz deps
# cf checker
- cfchecker=2.0.9
- cdat-lite=6.0rc2
# qa dkrz
- qa-dkrz=0.5.17
# compliance checker ioos
- compliance-checker=3.0.0
- pip:
  - genshi
  - sphinx-autoapi
#  - eventlet==0.19.0
  - cdo==1.3.2
