name: hummingbird
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7.12
- pyopenssl
- cryptography
- pyyaml
- curl
# buildout
- mako
# tests
- pytest
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=3.2.6
- owslib
- nginx
- supervisor
- gunicorn
- gevent
- eventlet
# cdo
- cdo
- python-cdo
# cf checker
- cfchecker=2.0.9
- cdat-lite=6.0rc2
# qa dkrz
- qa-dkrz=0.5.14
# compliance checker ioos
- compliance-checker=2.3.0
- pip:
  - genshi
  - sphinx-autoapi
#  - eventlet==0.19.0
