name: hummingbird
channels:
- conda-forge
- birdhouse
- defaults
dependencies:
- alabaster=0.7.8=py27_0
- babel=2.3.3=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_0
- cdat-lite=6.0rc2=py27_0
- cdo=1.7.1=1
- cf_units=1.1.1=py27_0
- cfchecker=2.0.9=py27_0
- cffi=1.6.0=py27_0
- compliance-checker=2.1.0=py27_0
- cryptography=1.4=py27_0
- curl=7.45.0=0
- decorator=4.0.10=py27_0
- docutils=0.12=py27_2
- enum34=1.1.6=py27_0
- eventlet=0.16.1=py27_0
- expat=2.1.0=1
- gdal=1.10.1=py27_0
- gevent=1.1.1=py27_0
- gmp=6.1.1=0
- greenlet=0.4.10=py27_0
- gunicorn=19.1.0=py27_0
- hdf5=1.8.15.1=2
- htmltmpl=1.22=py27_1
- icu=56.1=3
- idna=2.0=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.14=py27_0
- ipython=4.2.0=py27_2
- ipython_genutils=0.1.0=py27_0
- isl=0.12.2=0
- jasper=1.900.1=2
- jinja2=2.8=py27_0
- jpeg=9b=0
- krb5=1.14.2=0
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libiconv=1.14=2
- libnetcdf=4.3.3.1=3
- libuuid=1.0.3=0
- libxml2=2.9.3=8
- libxslt=1.1.28=0
- lxml=3.6.0=py27_0
- mako=1.0.4=py27_0
- markupsafe=0.23=py27_2
- meld3=1.0.2=py27_0
- mkl=11.3.3=0
- netcdf-fortran=4.4.3=2
- netcdf4=1.2.4=np111py27_1
- nginx=1.10.1=1
- numpy=1.11.0=py27_2
- openssl=1.0.2h=1
- owslib=0.11.2=py27_59
- pastedeploy=1.5.2=py27_1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.31=0
- petulant-bear=0.2.0=py27_0
- pexpect=4.1.0=py27_0
- pickleshare=0.7.2=py27_0
- pip=8.1.2=py27_0
- proj.4=4.9.2=0
- ptyprocess=0.5.1=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_1
- pygments=2.1.3=py27_0
- pyopenssl=0.16.0=py27_0
- pyproj=1.9.5.1=py27_0
- pytest=2.9.2=py27_0
- python=2.7.11=5
- python-cdo=1.3.0=py27_0
- python-dateutil=2.5.2=py27_0
- python-decorator=4.0.10=py27_0
- python-magic=0.4.6=py27_1
- python-pathlib2=2.1.0=py27_0
- python-simplegeneric=0.8.1=py27_0
- pytz=2016.3=py27_0
- pywps=3.2.6=py27_0
- pyyaml=3.11=py27_4
- qa-dkrz=0.5.13=0
- readline=6.2=2
- requests=2.9.2=py27_0
- setuptools=23.0.0=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.4.1=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.13.0=0
- supervisor=3.1.3=py27_1
- tk=8.5.18=0
- traitlets=4.2.1=py27_0
- udunits2=2.2.20=1
- wheel=0.29.0=py27_0
- wicken=0.2.0=py27_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - cf-units==1.1.1
  - genshi==0.7
  - ipython-genutils==0.1.0
  - simplegeneric==0.8.1
  - sphinx-rtd-theme==0.1.9
