name: hummingbird
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=2.7.12
- pyopenssl
- cryptography
- pyyaml
- curl
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=4.0.0
- owslib
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.1.2
- eventlet=0.19.0
# cdo
- cdo=1.7.1
#- python-cdo=1.3.0
- proj4=4.9.3  # fix cdo and qa-dkrz deps
#- jpeg=9b # fix cdo and qa-dkrz deps
# cf checker
- cfchecker=2.0.9
- cdat-lite=6.0rc2
# qa dkrz
- qa-dkrz=0.6.0
- wget=1.18
# compliance checker ioos
- compliance-checker=3.0.0
- pip:
  - genshi
  - sphinx-autoapi
  - cdo==1.3.2
