name: hummingbird
channels:
- defaults
- birdhouse
- ioos
dependencies:
- python=2.7.12
- pyopenssl=0.16.0
- cryptography=1.4
- pyyaml=3.11
- curl=7.45.0
# buildout
- mako=1.0.4
# tests
- pytest=2.9.2
# ipython
- ipython=4.2.0
# docs
- sphinx=1.4.1
# wps
- pywps=3.2.6
- owslib=0.11.2
- nginx=1.10.1
- supervisor=3.1.3
- gunicorn=19.1.0
- gevent=1.1.1
- eventlet=0.16.1
# cdo
- cdo=1.7.0
- jpeg==8d
# cf checker
- cfchecker=2.0.9
- cdat-lite=6.0rc2
# qa dkrz
- qa-dkrz=0.5.13
# compliance checker ioos
- compliance-checker=2.1.0
- pip:
  - genshi==0.7
  - cdo==1.3.0
#  - eventlet==0.19.0
