name: hummingbird
channels:
- birdhouse
- conda-forge
- defaults
- pcmdi
- uvcdat
dependencies:
- python=2.7
- pyopenssl
- cryptography
- pyyaml
- curl
- icu=58.1
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=4.0.0
- owslib
- nginx=1.10.3
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.2
- eventlet=0.19.0
- lxml=3.7
- libxslt=1.1.29
# cdo
- python-cdo
- cdo=1.8.1
- proj4=4.9.3  # fix cdo and qa-dkrz deps
#- jpeg=9b # fix cdo and qa-dkrz deps
# cf checker
- cfchecker=2.0.9
- cdat-lite=6.0rc2
# qa dkrz
- qa-dkrz=0.6.3
- wget=2.2
# compliance checker ioos
- compliance-checker=3.0.2
# cmor
- cmor=3.2.2
- cmip6-cmor-tables=3.2.3
- libnetcdf=4.4.1
- pip:
  - genshi
  - sphinx-autoapi
